"""Compile-time configuration baked into the PyInstaller binary by CI.

AUTO-GENERATED by scripts/write_bundled_config.py — do not edit manually.
To regenerate: python scripts/write_bundled_config.py
"""

AIDREAM_SERVER_URL_LIVE: str = 'https://server.app.matrxserver.com'
SUPABASE_URL: str = 'https://txzxabzwovsujtloxrus.supabase.co'
SUPABASE_PUBLISHABLE_KEY: str = 'sb_publishable_4pvkRT-9-_dB0PWqF1sp1w_W9leRIoW'


def apply() -> None:
    """Inject bundled config into os.environ if not already set."""
    import os

    _vals = {
        "AIDREAM_SERVER_URL_LIVE": AIDREAM_SERVER_URL_LIVE,
        "SUPABASE_URL": SUPABASE_URL,
        "SUPABASE_PUBLISHABLE_KEY": SUPABASE_PUBLISHABLE_KEY,
    }
    for key, val in _vals.items():
        if val and not os.environ.get(key):
            os.environ[key] = val
