#!/usr/bin/env python3
"""Write compile-time config into app/bundled_config.py before PyInstaller runs.

Called by CI (and optionally by a developer locally) to bake the current
environment's API URLs and publishable keys into the binary.

Usage:
    python scripts/write_bundled_config.py

Required environment variables (read from CI secrets / local .env):
    AIDREAM_SERVER_URL_LIVE      — e.g. https://server.app.matrxserver.com
    SUPABASE_URL                 — e.g. https://txzxabzwovsujtloxrus.supabase.co
    SUPABASE_PUBLISHABLE_KEY     — the publishable (anon) key from Supabase

Exit code 0 on success, 1 if any required var is missing.
"""

import os
import sys
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / "app" / "bundled_config.py"

# Load .env so running locally also works
_env_file = ROOT / ".env"
if _env_file.exists():
    from dotenv import load_dotenv
    load_dotenv(dotenv_path=_env_file)

AIDREAM_SERVER_URL = os.environ.get("AIDREAM_SERVER_URL_LIVE", "").strip()
SUPABASE_URL = os.environ.get("SUPABASE_URL", "").strip()
SUPABASE_KEY = os.environ.get("SUPABASE_PUBLISHABLE_KEY", "").strip()

missing = [k for k, v in [
    ("AIDREAM_SERVER_URL_LIVE", AIDREAM_SERVER_URL),
    ("SUPABASE_URL", SUPABASE_URL),
    ("SUPABASE_PUBLISHABLE_KEY", SUPABASE_KEY),
] if not v]

if missing:
    print(f"ERROR: Missing required env vars: {', '.join(missing)}", file=sys.stderr)
    print("Set them in your environment or in the root .env file.", file=sys.stderr)
    sys.exit(1)

content = textwrap.dedent(f'''\
    """Compile-time configuration baked into the PyInstaller binary by CI.

    AUTO-GENERATED by scripts/write_bundled_config.py — do not edit manually.
    To regenerate: python scripts/write_bundled_config.py
    """

    AIDREAM_SERVER_URL_LIVE: str = {AIDREAM_SERVER_URL!r}
    SUPABASE_URL: str = {SUPABASE_URL!r}
    SUPABASE_PUBLISHABLE_KEY: str = {SUPABASE_KEY!r}


    def apply() -> None:
        """Inject bundled config into os.environ if not already set."""
        import os

        _vals = {{
            "AIDREAM_SERVER_URL_LIVE": AIDREAM_SERVER_URL_LIVE,
            "SUPABASE_URL": SUPABASE_URL,
            "SUPABASE_PUBLISHABLE_KEY": SUPABASE_PUBLISHABLE_KEY,
        }}
        for key, val in _vals.items():
            if val and not os.environ.get(key):
                os.environ[key] = val
''')

TARGET.write_text(content, encoding="utf-8")
print(f"✅  Wrote bundled config to {TARGET}")
print(f"   AIDREAM_SERVER_URL_LIVE  = {AIDREAM_SERVER_URL}")
print(f"   SUPABASE_URL             = {SUPABASE_URL}")
print(f"   SUPABASE_PUBLISHABLE_KEY = {'*' * 8}{SUPABASE_KEY[-6:]}")
